# Generated by Django 3.1.7 on 2021-05-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0007_detail_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='otp',
            field=models.TextField(null=True),
        ),
    ]
